// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for ACMProviderHintsPlatform.
const (
	Baremetal ACMProviderHintsPlatform = "baremetal"
	Kubevirt  ACMProviderHintsPlatform = "kubevirt"
)

// Defines values for ClusterStatus.
const (
	DELETED      ClusterStatus = "DELETED"
	FAILED       ClusterStatus = "FAILED"
	PENDING      ClusterStatus = "PENDING"
	PROVISIONING ClusterStatus = "PROVISIONING"
	READY        ClusterStatus = "READY"
)

// Defines values for ErrorType.
const (
	ALREADYEXISTS       ErrorType = "ALREADY_EXISTS"
	INTERNAL            ErrorType = "INTERNAL"
	INVALIDARGUMENT     ErrorType = "INVALID_ARGUMENT"
	NOTFOUND            ErrorType = "NOT_FOUND"
	PERMISSIONDENIED    ErrorType = "PERMISSION_DENIED"
	UNAUTHENTICATED     ErrorType = "UNAUTHENTICATED"
	UNAVAILABLE         ErrorType = "UNAVAILABLE"
	UNPROCESSABLEENTITY ErrorType = "UNPROCESSABLE_ENTITY"
)

// Defines values for HealthStatus.
const (
	HEALTHY   HealthStatus = "HEALTHY"
	UNHEALTHY HealthStatus = "UNHEALTHY"
)

// Defines values for HealthCheckStatus.
const (
	FAIL HealthCheckStatus = "FAIL"
	PASS HealthCheckStatus = "PASS"
)

// ACMProviderHints ACM-specific provider hints
type ACMProviderHints struct {
	// AgentLabels Labels to match agents (for baremetal)
	AgentLabels *map[string]string `json:"agent_labels,omitempty"`

	// BaseDomain Base domain for the cluster (e.g., "example.com")
	BaseDomain *string `json:"base_domain,omitempty"`

	// InfraEnv Name of the InfraEnv to use (for baremetal)
	InfraEnv *string `json:"infra_env,omitempty"`

	// Platform Target platform for the cluster
	Platform *ACMProviderHintsPlatform `json:"platform,omitempty"`

	// ReleaseImage Optional override for the release image
	ReleaseImage *string `json:"release_image,omitempty"`
}

// ACMProviderHintsPlatform Target platform for the cluster
type ACMProviderHintsPlatform string

// ClusterInstance A cluster resource managed by ACM/HyperShift
type ClusterInstance struct {
	// ApiEndpoint Kubernetes API endpoint URL (available when READY)
	ApiEndpoint *string `json:"api_endpoint,omitempty"`

	// ConsoleUri OpenShift console URI (available when READY)
	ConsoleUri *string `json:"console_uri,omitempty"`

	// CreateTime Timestamp when the cluster was created
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Kubeconfig Base64-encoded kubeconfig for cluster access. Populated when cluster status is READY. Empty during PENDING, PROVISIONING, or FAILED states.
	Kubeconfig *string `json:"kubeconfig,omitempty"`

	// Metadata Optional metadata for the cluster
	Metadata *ClusterMetadata `json:"metadata,omitempty"`

	// Nodes Node configuration for the cluster
	Nodes ClusterNodes `json:"nodes"`

	// Path Resource path for this cluster
	Path *string `json:"path,omitempty"`

	// ProviderHints Provider-specific configuration hints
	ProviderHints *ProviderHints `json:"provider_hints,omitempty"`

	// Status Current status of the cluster
	Status *ClusterStatus `json:"status,omitempty"`

	// StatusMessage Human-readable message about the current status
	StatusMessage *string `json:"status_message,omitempty"`

	// UpdateTime Timestamp when the cluster was last updated
	UpdateTime *time.Time `json:"update_time,omitempty"`

	// Version OpenShift version for the cluster (e.g., "4.14.0", "4.15.2")
	Version string `json:"version"`
}

// ClusterList Paginated list of clusters
type ClusterList struct {
	// NextPageToken Token to fetch the next page of results
	NextPageToken *string `json:"next_page_token,omitempty"`

	// Results List of clusters
	Results *[]ClusterInstance `json:"results,omitempty"`
}

// ClusterMetadata Optional metadata for the cluster
type ClusterMetadata struct {
	// Annotations Key-value annotations for the cluster
	Annotations *map[string]string `json:"annotations,omitempty"`

	// Labels Key-value labels for the cluster
	Labels *map[string]string `json:"labels,omitempty"`
}

// ClusterNodes Node configuration for the cluster
type ClusterNodes struct {
	// ControlPlane Control plane node specification
	ControlPlane ControlPlaneSpec `json:"control_plane"`

	// Workers Worker node specification
	Workers *WorkerSpec `json:"workers,omitempty"`
}

// ClusterStatus Current status of the cluster
type ClusterStatus string

// ControlPlaneSpec Control plane node specification
type ControlPlaneSpec struct {
	// Count Number of control plane nodes
	Count int `json:"count"`

	// Cpu Number of CPU cores per control plane node
	Cpu int `json:"cpu"`

	// Memory Memory per control plane node (e.g., "16GB", "32GB")
	Memory string `json:"memory"`

	// Storage Storage per control plane node (e.g., "120GB", "500GB")
	Storage *string `json:"storage,omitempty"`
}

// Error RFC 7807 compliant error response
type Error struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Instance Unique identifier for this specific error occurrence. Useful for
	// tracking and debugging.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int32 `json:"status,omitempty"`

	// Title Short, human-readable summary of the problem
	Title string `json:"title"`

	// Type URI reference identifying the problem type. This is the canonical
	// error code.
	Type ErrorType `json:"type"`
}

// ErrorType URI reference identifying the problem type. This is the canonical
// error code.
type ErrorType string

// Health Health status singleton resource
type Health struct {
	// Checks Individual health checks
	Checks *[]HealthCheck `json:"checks,omitempty"`

	// Message Optional message about the health status
	Message *string `json:"message,omitempty"`

	// Path Canonical path of the resource
	Path *string `json:"path,omitempty"`

	// Status Health status
	Status HealthStatus `json:"status"`
}

// HealthStatus Health status
type HealthStatus string

// HealthCheck Individual health check result
type HealthCheck struct {
	// Message Optional message about this check
	Message *string `json:"message,omitempty"`

	// Name Name of the health check
	Name string `json:"name"`

	// Status Status of this check
	Status HealthCheckStatus `json:"status"`
}

// HealthCheckStatus Status of this check
type HealthCheckStatus string

// ProviderHints Provider-specific configuration hints
type ProviderHints struct {
	// Acm ACM-specific provider hints
	Acm *ACMProviderHints `json:"acm,omitempty"`
}

// WorkerSpec Worker node specification
type WorkerSpec struct {
	// Count Number of worker nodes
	Count int `json:"count"`

	// Cpu Number of CPU cores per worker node
	Cpu int `json:"cpu"`

	// Memory Memory per worker node (e.g., "16GB", "32GB")
	Memory string `json:"memory"`

	// Storage Storage per worker node (e.g., "120GB", "500GB")
	Storage *string `json:"storage,omitempty"`
}

// ClusterPath defines model for ClusterPath.
type ClusterPath = string

// ListClustersParams defines parameters for ListClusters.
type ListClustersParams struct {
	// PageToken Token for fetching the next page of results
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`

	// MaxPageSize Maximum number of results to return per page
	MaxPageSize *int32 `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`
}

// CreateClusterParams defines parameters for CreateCluster.
type CreateClusterParams struct {
	// Id Client-assigned cluster identifier
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// CreateClusterJSONRequestBody defines body for CreateCluster for application/json ContentType.
type CreateClusterJSONRequestBody = ClusterInstance

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all clusters
	// (GET /clusters)
	ListClusters(w http.ResponseWriter, r *http.Request, params ListClustersParams)
	// Create a new cluster
	// (POST /clusters)
	CreateCluster(w http.ResponseWriter, r *http.Request, params CreateClusterParams)
	// Delete a cluster
	// (DELETE /clusters/{cluster})
	DeleteCluster(w http.ResponseWriter, r *http.Request, cluster ClusterPath)
	// Get cluster details
	// (GET /clusters/{cluster})
	GetCluster(w http.ResponseWriter, r *http.Request, cluster ClusterPath)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all clusters
// (GET /clusters)
func (_ Unimplemented) ListClusters(w http.ResponseWriter, r *http.Request, params ListClustersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new cluster
// (POST /clusters)
func (_ Unimplemented) CreateCluster(w http.ResponseWriter, r *http.Request, params CreateClusterParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a cluster
// (DELETE /clusters/{cluster})
func (_ Unimplemented) DeleteCluster(w http.ResponseWriter, r *http.Request, cluster ClusterPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get cluster details
// (GET /clusters/{cluster})
func (_ Unimplemented) GetCluster(w http.ResponseWriter, r *http.Request, cluster ClusterPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListClusters operation middleware
func (siw *ServerInterfaceWrapper) ListClusters(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListClustersParams

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	// ------------- Optional query parameter "max_page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "max_page_size", r.URL.Query(), &params.MaxPageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_page_size", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListClusters(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCluster operation middleware
func (siw *ServerInterfaceWrapper) CreateCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateClusterParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCluster(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCluster operation middleware
func (siw *ServerInterfaceWrapper) DeleteCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "cluster" -------------
	var cluster ClusterPath

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", chi.URLParam(r, "cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCluster(w, r, cluster)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCluster operation middleware
func (siw *ServerInterfaceWrapper) GetCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "cluster" -------------
	var cluster ClusterPath

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", chi.URLParam(r, "cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCluster(w, r, cluster)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/clusters", wrapper.ListClusters)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/clusters", wrapper.CreateCluster)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/clusters/{cluster}", wrapper.DeleteCluster)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/clusters/{cluster}", wrapper.GetCluster)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})

	return r
}

type ListClustersRequestObject struct {
	Params ListClustersParams
}

type ListClustersResponseObject interface {
	VisitListClustersResponse(w http.ResponseWriter) error
}

type ListClusters200JSONResponse ClusterList

func (response ListClusters200JSONResponse) VisitListClustersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListClusters400ApplicationProblemPlusJSONResponse Error

func (response ListClusters400ApplicationProblemPlusJSONResponse) VisitListClustersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListClusters500ApplicationProblemPlusJSONResponse Error

func (response ListClusters500ApplicationProblemPlusJSONResponse) VisitListClustersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateClusterRequestObject struct {
	Params CreateClusterParams
	Body   *CreateClusterJSONRequestBody
}

type CreateClusterResponseObject interface {
	VisitCreateClusterResponse(w http.ResponseWriter) error
}

type CreateCluster201JSONResponse ClusterInstance

func (response CreateCluster201JSONResponse) VisitCreateClusterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateCluster400ApplicationProblemPlusJSONResponse Error

func (response CreateCluster400ApplicationProblemPlusJSONResponse) VisitCreateClusterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateCluster409ApplicationProblemPlusJSONResponse Error

func (response CreateCluster409ApplicationProblemPlusJSONResponse) VisitCreateClusterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateCluster422ApplicationProblemPlusJSONResponse Error

func (response CreateCluster422ApplicationProblemPlusJSONResponse) VisitCreateClusterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateCluster500ApplicationProblemPlusJSONResponse Error

func (response CreateCluster500ApplicationProblemPlusJSONResponse) VisitCreateClusterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteClusterRequestObject struct {
	Cluster ClusterPath `json:"cluster"`
}

type DeleteClusterResponseObject interface {
	VisitDeleteClusterResponse(w http.ResponseWriter) error
}

type DeleteCluster204Response struct {
}

func (response DeleteCluster204Response) VisitDeleteClusterResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteCluster404ApplicationProblemPlusJSONResponse Error

func (response DeleteCluster404ApplicationProblemPlusJSONResponse) VisitDeleteClusterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCluster500ApplicationProblemPlusJSONResponse Error

func (response DeleteCluster500ApplicationProblemPlusJSONResponse) VisitDeleteClusterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetClusterRequestObject struct {
	Cluster ClusterPath `json:"cluster"`
}

type GetClusterResponseObject interface {
	VisitGetClusterResponse(w http.ResponseWriter) error
}

type GetCluster200JSONResponse ClusterInstance

func (response GetCluster200JSONResponse) VisitGetClusterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCluster404ApplicationProblemPlusJSONResponse Error

func (response GetCluster404ApplicationProblemPlusJSONResponse) VisitGetClusterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetCluster500ApplicationProblemPlusJSONResponse Error

func (response GetCluster500ApplicationProblemPlusJSONResponse) VisitGetClusterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all clusters
	// (GET /clusters)
	ListClusters(ctx context.Context, request ListClustersRequestObject) (ListClustersResponseObject, error)
	// Create a new cluster
	// (POST /clusters)
	CreateCluster(ctx context.Context, request CreateClusterRequestObject) (CreateClusterResponseObject, error)
	// Delete a cluster
	// (DELETE /clusters/{cluster})
	DeleteCluster(ctx context.Context, request DeleteClusterRequestObject) (DeleteClusterResponseObject, error)
	// Get cluster details
	// (GET /clusters/{cluster})
	GetCluster(ctx context.Context, request GetClusterRequestObject) (GetClusterResponseObject, error)
	// Health check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListClusters operation middleware
func (sh *strictHandler) ListClusters(w http.ResponseWriter, r *http.Request, params ListClustersParams) {
	var request ListClustersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListClusters(ctx, request.(ListClustersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListClusters")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListClustersResponseObject); ok {
		if err := validResponse.VisitListClustersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCluster operation middleware
func (sh *strictHandler) CreateCluster(w http.ResponseWriter, r *http.Request, params CreateClusterParams) {
	var request CreateClusterRequestObject

	request.Params = params

	var body CreateClusterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCluster(ctx, request.(CreateClusterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCluster")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateClusterResponseObject); ok {
		if err := validResponse.VisitCreateClusterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCluster operation middleware
func (sh *strictHandler) DeleteCluster(w http.ResponseWriter, r *http.Request, cluster ClusterPath) {
	var request DeleteClusterRequestObject

	request.Cluster = cluster

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCluster(ctx, request.(DeleteClusterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCluster")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteClusterResponseObject); ok {
		if err := validResponse.VisitDeleteClusterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCluster operation middleware
func (sh *strictHandler) GetCluster(w http.ResponseWriter, r *http.Request, cluster ClusterPath) {
	var request GetClusterRequestObject

	request.Cluster = cluster

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCluster(ctx, request.(GetClusterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCluster")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetClusterResponseObject); ok {
		if err := validResponse.VisitGetClusterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
