// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaX3PbtrL/Khi0D0ku9ceOk976PtxRZNXWVJY1lpxzOpGPBiJXEhoQYAFQtprRdz8D",
	"gCApkbLsps3pw3kjCWB3sdj97R/wCw5FnAgOXCt8/gUnRJIYNEj71mWp0iBHRK/MawQqlDTRVHB87geR",
	"BCVSGQKiEXBNFxQkDjA1UxKzMMCcxIDPcegW4ABL+C2lEiJ8rmUKAVbhCmJiWMTkcQB8afi9fxvgmHL/",
	"ehIYchqkIfyvT6Txe7vx4/2r7KFx/6UdvD/Z+u+v//97HGC9SQxjpSXlS7zdbj0ru7tO93okxZpGIK9o",
	"tv/dLXa61w2VQEgXNERJNhet7OQAJ1IkIDUFu5IsgesZI3Ng7j2KqCFD2Ghn3p5MwR7LgSWAtEAx0eEK",
	"WbIKvVoIieZEQgyasNfF3sT8Vwi1oTMnCmaRiIlR/f5OPhAFyA0iQ0qvAGXngV5Bc9kM0BTDI4kTBs1Q",
	"xFP8uqo/c6oLSWbA11UOQxIDEgtLuW+m9fjabCNVcFj6gnLCiF4IGTvCC5Iyjc/x53QOayo13lfThMgl",
	"aORX7e8JBxh4GuPzT2USuQT4vkYCCQyMCmlMllDd303iThOJNUhJI8h5ZguRW1i1upqzynynz5UmPKzh",
	"1slPJ3evmHCyhAjNN6jTvW5dbRKQ4xVd6KopJnQGPEoE5bpK+ud0DpKDBoU6oz7yE9Hd7QC9ImtCGZkz",
	"QA8r4Oi217n45bX1WBLdcLbxHlvRXii4EgxmqaR1ugNuRUXZNHR32/8aZhKIhpmmcY3qJjQGpUmcOKpl",
	"S38gCrm1EQ6wMRxirCwiGhqW2DN4G3sKBV/QZb2XvT9rAA9FBBEqplpb8VKQMASlmmgkkpQZWZygflhp",
	"olOFqHIKaaJenOgNilIjARr1hhf94WWARrc3H/vj/s3QvgmJfur0B70LuxxU8zlbMb4QEW2B93sJC3yO",
	"v2sV8aCVYWUrs9ZrP30bYC4iZ2vPWDe0c7eBCwcVpd16AzfDmVNRVfZkB0tFBFGteNMoR5Mj+/TIPVt5",
	"mH9K6t2YYEKGPZBnbnbsJufLZjEoVQsoV2lMeMMIb10gm4fIXKTaWW0qJXCdGcRzNpom0R/2C0aURo7A",
	"H3eONUhluR1GgGzK4Sh01jw5a7anOHt+1zytDUbbchrxKefsTfN+H3UD/NggkDQ8nrpsxyYUyhDIbetL",
	"9rQ1NBKWSsJKpocDrChfpozInZQmY0bC2FtmQ4Fc0xAa3vyaURg3qWj5RdsiEAyoqkHqEVlSbgGCUaVN",
	"cC1JsQv5HB71LCFLmGnxGWoOYGI+m3i8AJNWGM2bNcisMZQlqJTZtKYmMLqhCs1BVSqqIX6uq+TRr4iQ",
	"REqyeTJkXpcw60CA9rBWkxTsxUnOhSZm1ddkbD/DprEmLAVUolfDu7Kjr84VC86O1HGmTyh26BF9L60T",
	"ESAXxFJp93ZUraHgWgo2SxjhcNQW3OSRmTtOIDQSPQj5OatAnlr6DzvNLdpDg10R7g/vepxj+15xs4O9",
	"Pq+tZpdZOMYBLsdjHGAbu3GAXVTGAb7oDXqT3kVt6llRQlUeNwPZDSEDccgXJvZQag4h9clflky/3Tef",
	"YRrPQVoHrlA3vhyTRxqbbbpCzD2f5OJTrmFpYCzAYZLWWE5Ovju6Q6GQoFACsoYZLtE/raMfQyzkpsri",
	"2n4/QLWIKCfvLz+4ePL21Dy93kkqzGgd7CktZG3gHruB42xP257vu3a7hrEZPxrY3EE6HeeaqLPonpRC",
	"1qRXP3XRD//b/gEZD2KUcI3AzDSInwiuoGI6EWhC2dGEBR7Nph0k5EWyFi57E6HLXkKoLyMP1T13nP6W",
	"llsJRUKY83DiFxya6E7BImVm6pRrScLPJlMmPEIRzNPlkvJlc8rLSU0qaUPCAg5KqA7gwtVkMvKgEDrT",
	"zYlSrt+e4jr71VSzOkNaCakDtNrVq0rjmMiNx5xEijmDuE5I96Giwts+yvfmNbkxGimRQ2ZtE02MYqly",
	"4Ea44DQkbMqdhs3+nN482vWHHzuD/sWsc3t5d90bTnCAhzeT2U83d0MDcZ2BRb1Z75/98WRsMLF3e90f",
	"G1CcXfSGfYuDd8PO3eSqN5z0u52J/dIfTnq3w87ADX7s9AedD4OefRvd3nR747F5n5klk1+M6T/3GPc8",
	"yY76w6jzoCsgrK5Ccd/9sZv0j4EWPC/Nq+C7gvBzjfX0eUTXNEoJQytHM5v5zMTJCdI1a6pJkwGHA6VG",
	"KTXaLzJW5b3VNmbqm3/eWFzVltlqSSEFzDkOz6keDjrdnozeHK96ncHk6hdrKf75/pgVZFReXB9k2yjX",
	"BO6TLwmsTeQdzaJGyPf/ghIhW7PNjdKd+XMNKsvmK3b5cgMxhbhlXXNcrq37VB+wLNNLUHZcyrpKEuRJ",
	"V2c8zlKr4+dtpQwOHvs2wEeawH646ATvpsMH2sFhfMybK/3n2vS8lOVWRHNjL0wH63O0h4KUKudj7a/O",
	"90qU/4xEr0Tum2R49fy+ZWq3dY134WsrEtqTzG5VLrrXaCRFhmGptMCkdaLOW60l1at03gxF3IrC2KCM",
	"t6q9/ToYKq44OqO+Tbxsz9mkDqUOblbsozUl6BYidEU06kRrk89FyF8KXdtmdWxKqFed7vVrm40VLevm",
	"lE+5TT4MJ6pQQqT2qHFBjb7mqbb0RBrtULsw1LKdWKqZ0HnHEDG6gHATMt8yN+umPCQJmVNGjUcgykOW",
	"RmZjth1MBQ9QBAzck6GaBftYcKqFdBnklH/3HTL6voWlkdH5v+9ITHkDvXlj4O/8zRu0g/KJG8vUPNkk",
	"dko2nI2lSSKkhmiUXWkoM8VfXgTF7cne9I+u72VnX2w4iWmIXs2JgggJ7o+jH5MljEErVLTcBUed7jW6",
	"SuevHcmbBNyOLK3uba8z6QXIla2B7UXbXJDREEzVUFhgJyHhCtBps10xwIeHhyaxw00hl61srWoN+t3e",
	"cNxrmDVFfoyNQN6CvE2OSjaJSx1GfNJsu9UiAU4Sis/x22a7eYZdzmJhr5W3ps6/4CXouu6zTiVXiKCk",
	"0m0jjBXmXrp+ceXIns80sZXEqbAfZe2xbqlhV7pa/VTfnjMuZ/tzPls/0KKzl6u/pSA3xe1qqflXvlCt",
	"IFAFWl2Vj3gO3xkfU8tJqx2Lg4m73KpjHZNH13tU9HfY4Z43H961awqlvMFw0m4/3WLY3ts2pK1X7Vme",
	"ttseDsEFNpIkLIt+rV+V60EXgjyjHWl7sBZsj3Q5twE+e5J9VmP9z8vEcPV7jQB9viaMRsiEDlAWvt99",
	"W/4mCSbMmjxIV3/bYJaVql5JZX8xwY8sdzrr+N6UE6Ku0921l3LGCzk8VIONjTW7l56mdi0uDzyKm1BC",
	"1IaHKym4SNX/Tbl11vySU2buTuMYIko0sA16oHqFiL9Zy5DfNhXQZW+CWpWbgX60nXItUCIY27nZMxUO",
	"5aCUK5t34cDtsVs0TZ/Cgy6jwHWDKEWXHKKcQ/Ufiz1fpNGOA+79MvHC/yXuXb4CSn8Q0ebPdrii/7+b",
	"GJkKalvx95O/ln39vy2FXXGqqb0a+xt4/1n7x2/H36uCMGPdGwSPVLl70bPT028nxh1XPuUp/voQ0l8n",
	"/i1B0Xl8BmqlO5kqLm4D3Kq5gLQ4yUBDXeXvDFLleavNWDwbB4/50D4solpUnPISLO4C7ANlDM0BSYjF",
	"GiK0kCK2GYraKA0xEjwssbOtZtBQi4MXdkcHcbDuNIoprfIvaTVZwdnh/9QKZez68tm39yUuNFqIlEd/",
	"S7N1B1TY0qFQ/mQ+ra35aUKZcoZZdE98KMtrMKrV3s8O1WT6EvRfZDLt/0RgyVTzXwustcBLKFI/r6mD",
	"uLnKu/ZHDXKn2e3bDccLuUvQV0UT+y8ynivf8j3YnaEq28BmT11Xe23WTE++Y+3+e7Xarks1O6M+Wp8Q",
	"lqzISV7At0hCW/lX4zUZ1UPoWrRaUK48Vfn31xj8ge6+a1zXrfXN8PvtvwMAAP//G4Zw864sAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
