// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaX3Mit7L/KiolD+u9wx97neTG9+EWi4lNBWPK4D0ntfhQYqYBZWekiaTBJlt891P6",
	"NzMwg7GzyZ48nDdAUrfU6v519098xiFPUs6AKYkvPuOUCJKAAmG+deNMKhAjolb6awQyFDRVlDN84QeR",
	"AMkzEQKiETBFFxQEDjDVU1K9MMCMJIAvcGgX4AAL+C2jAiJ8oUQGAZbhChKiVSTkaQBsqfV9/y7ACWX+",
	"62mgxSkQWvC/PpLG7+3Gjw9v3IfGw+d28P3p1v9+8v/f4gCrTaoVSyUoW+LtdutVmdN1ujcjwdc0AnFN",
	"3fl3j9jp3jRkCiFd0BClbi5amckBTgVPQSgKZiVZAlOzmMwhtt+jiGoxJB7tzNvbU7CncmAEIMVRQlS4",
	"QkasRG8WXKA5EZCAIvFJcTY+/xVCpeXMiYRZxBOiTb9/kvdEArKDSItSK0DuPtAbaC6bAZpieCJJGkMz",
	"5MkUn1Ttp291IcgM2LqqYUgSQHxhJPf1tB5b62NkEg7vvpCcxkQtuEis4AXJYoUv8KdsDmsqFN4304SI",
	"JSjkV+2fCQcYWJbgi49lEfkO8EPNDgTEoE1IE7KE6vluU3ubiK9BCBpBrtMtRHZh1etq7srFTp9JRVhY",
	"o62T304eXglhZAkRmm9Qp3vTut6kIMYrulBVV0zpDFiUcspUVfTP2RwEAwUSdUZ95Cei+7sBekPWhMZk",
	"HgN6XAFDd73O5S8nJmJJdMvijY/YivVCziSPYZYJWmc7YGaryE1D93f9L1EmgCiYKZrUmG5CE5CKJKmV",
	"Wvb0RyKRXRvhAGvHIdrLIqKgYYS9QLd2oIgog1bfCljgC/xNqwDRlgOYlrviGz99G2DGI3tBL1g3NHO3",
	"gcXQyiHvvFfoYeeJVJbd38ZyAbuylWwaZQg+ck4Pd7OVx8bndr0LpBpnFVHZSw87tpPzZbMEpKyNwuss",
	"IayhN2/8xs1DZM4zZa86EwKYQk7/Cw6apdEfdqaYSIWsgD/uUWsQ0mg7HDZuymHoPm+enjfbU+w+f9c8",
	"q0XwbTn3fsw1e9d82IeqAD81CKQND0K2RDBZWGoBuW99dp+2WkYaZ4LEJdfDAZaULbOYiJ06wCkjYeI9",
	"syFBrGkIDe9+zShMmpS3/KJtgZ4DKtUdyJQzWXNzI7KkTN8LiqlUOjOVdrOLlwye1CwlS5gp/glqLmKi",
	"f9bJbAE6J+sb0GuQXqMlC5BZbGqCmqxihyoyB9VdUQXJS0MmTx1FeiFCkM2z+eamhF0HspuHt5qMupdk",
	"GOOK6FVfUu78DJvGmsQZoJK8Gt2VE31xoVVotqKOK33GsEOP7Hs1EY9Ap7wFXWbCnO2oWUPOlODxLI0J",
	"g6O+YCeP9NxxCqHe0SMXn1z5/tzSf5hpdtEeKuxu4eHwqcc5xu91BjsY7IvCamk26g0v+8MrHODR3e2H",
	"/rh/O7RfTSWAA/xTpz/oXeIAX/YGvYkeqyvcKlaobsjOQOZESGMd8mW9uZWaW8h86eRK0Xf7/jPMkjkI",
	"E8EV6TqYE/JEE31O28bYz6f59ilTsNR4FuAwzWpcJxffHd2jkAuQKAVRowyX5J/VyU8g4WJTVXFjfj8g",
	"tUgtp99fvbeJ5d2Z/nSyU13o0Trck4qL2gw+tgPH1Z61vd7v2u0axXr8aIazF2ltnFuizqV7QnBRU2f9",
	"1EU//G/7B6RDKKaEKQR6poZ8m3j2XScCRWh8tHKBJ31oiwl5i6m4LeN4aMuYEOqbsENdwz2jv2XlRryo",
	"DHMddvuFhia6l7DIYj11ypQg4SfKloiwCEUwz5ZLypbNKStXN5mgDQELOLhDeQAYrieTkUeF0LpuLpQy",
	"9e4M1/mvoiquc6QVFypAq127yixJiNh40EkFn8eQ1G3S/lAx4V0f5Wfzltxoi5TEIb22iSbasFRadCOM",
	"MxqSeMqshfX5rN083PWHHzqD/uWsc3d1f9MbTnCAh7eT2U+390ONcZ2Bgb1Z75/98WSsQbF3d9Mfa1Sc",
	"XfaGfQOE98PO/eS6N5z0u52J+aU/nPTuhp2BHfzQ6Q867wc97eMvva+9kDGj3up1oXINJK7rSezv/n51",
	"wReD4izvYKsou4LwU42b9FlE1zTKSIxWVqab+cISyW6kq9dUyyONAgeai1IRtN9WrMpnq+Uv6jky7xW2",
	"T3NOWTJIgWdWw0v6hYPRtbdH73fXvc5gcv2LcRD/+eGYFzgpr+4I3DHKXYD9yTcBxidy4q/oCvLzv6Ip",
	"cGu2uVPaO3+pQ7m6veKXr3cQ3Xob1TXXZdnP5+iy8p5eA6fjUn1V2kFeXnXGY1dEHb9vs8vg4LVvA3yE",
	"K/XDBWG6W/geYE3D5Fg0V2ja2kK8VM9WtmbHXln31Rdjj4UoWS682l9c2JUk/xkVXUncVynl6vV9zRpu",
	"a/lp7rsoEpqbdI8Pl90bNBLcYVgmDDAplcqLVmtJ1SqbN0OetKIw0SjjvWrvvBaGipeAzqhvKixDzeoa",
	"oUR0urYerSlBdxCha6JQJ1rrwi1C/u3kxnC6iW6W3nS6Nyem7CqY3eaUTZmpMrQmKlFKhPKocUm1veaZ",
	"MvJ4Fu1Iu9TS3EmMVLfpnCNEMV1AuAljzyzrdVMWkpTMaUx1RCDKwjiL9MEMa0o5C1AEMdhPWqpL9gln",
	"VHFhS8Up++YbpO19B0u9Rxv/nnuYsgZ6+1bD38Xbt2gH5VM75sw82aRmihuujH2w5JWectpsN9tuQpam",
	"XCiIRu5pQOoJ/hEgKF4h9qY7aWb25YaRhIbozZxIiBBn/r76CVnCGJREBXXNGep0b9B1Nj+xIm9TsEc2",
	"srp3vc6kFyDTwfYCQ3KbqjCmITjiyrloJyXhCtBZs13x0MfHxyYxw00uli23VrYG/W5vOO419JqiUsZ6",
	"Q97FvNOOSk6LS6QjNsbTq3kKjKQUX+B3zXbzHNuixuBiK2epLj7jJag6QlplgklEUFoh3kgcF/FQesaw",
	"jcleUDWx2Yk1YT9yTFm3xN2Vnig/1jN1OiYNVefr9gNsnXmk/C0DsSleKUs8YPlhsgJRFey1/T5iOb47",
	"PbqrE8Y6BihT+0hUpzohT5aGlPR32NGe0xBn7ZqWKacaTtvt58mG7YNhJE3nau7yrN32eAk285E0jV16",
	"bP0qLS1dbOQFzOQOLWtQ+QjxuQ3w+bPbcF3X/7xuO7ajr9lAn61JTCOkcwxIg/PffV39ulomsXF9ELYj",
	"N1nPNa/eSOW40VmSLHdId/yg+w4ua6Kxax65dDQyeKxmJZOUdh8RdTdbvCt4uNc5h8gNC1eCM57J/5sy",
	"E7T5o6FwYU+TBCJKFMQb9EjVChHk2D2XIgzNgK56E9SqPBr0o+2UKY5SHhsaovT2SSLKQErbSO/Cgj1j",
	"t+BRn8OFbkyBqQaRki4ZRLmG6n8W9mKSRjuBuPcXhFf+/+DBFjYg1Xsebf7swCueBHYrKN1qbStxf/rX",
	"qq//r0jhV4wqal7N/gbRf97+8evp96YgsfbuDYInKu2T6d8OhGyEORApPYtUcWgb4FbNW6DBpRgU1LXk",
	"1gFkXlCaSsGrsXCUD+3DEKpFoSkrwdAuoD3SOEZzQAISvoYILQRPTGUgN1JBgjgLS+oM2QsKanHn0pzo",
	"IO7U3UYxpVX+S1VNNj4//D+rwhi7sXP+9X2XcYUWPGPR39Jt7QUVvnQodT5bxyrjforQWFrHLGgNnzry",
	"5ogqufe/g2oRewXqL3KZ9n8CyJ1p/uuBtR54BUWp5S11EDdXOZ1+1CF3WGjPAxxvoK5AXRfs8l/kPNee",
	"iz1Im1DpDrDZM9f1Hv/p7OSpZPu/TWPtutKuM+qj9SmJ0xU5zRvnFklpK/9VR42TeghdCw4E5caTlf+u",
	"aoc/QLtbRrlurWepH7b/DgAA//9dwL60bisAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
