// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"time"
)

// Defines values for ACMProviderHintsPlatform.
const (
	Baremetal ACMProviderHintsPlatform = "baremetal"
	Kubevirt  ACMProviderHintsPlatform = "kubevirt"
)

// Defines values for ClusterStatus.
const (
	DELETING     ClusterStatus = "DELETING"
	FAILED       ClusterStatus = "FAILED"
	PENDING      ClusterStatus = "PENDING"
	PROVISIONING ClusterStatus = "PROVISIONING"
	READY        ClusterStatus = "READY"
)

// Defines values for ErrorType.
const (
	ALREADYEXISTS    ErrorType = "ALREADY_EXISTS"
	INTERNAL         ErrorType = "INTERNAL"
	INVALIDARGUMENT  ErrorType = "INVALID_ARGUMENT"
	NOTFOUND         ErrorType = "NOT_FOUND"
	PERMISSIONDENIED ErrorType = "PERMISSION_DENIED"
	UNAUTHENTICATED  ErrorType = "UNAUTHENTICATED"
	UNAVAILABLE      ErrorType = "UNAVAILABLE"
)

// Defines values for HealthStatus.
const (
	HEALTHY   HealthStatus = "HEALTHY"
	UNHEALTHY HealthStatus = "UNHEALTHY"
)

// Defines values for HealthCheckStatus.
const (
	FAIL HealthCheckStatus = "FAIL"
	PASS HealthCheckStatus = "PASS"
)

// ACMProviderHints ACM-specific provider hints
type ACMProviderHints struct {
	// AgentLabels Labels to match agents (for baremetal)
	AgentLabels *map[string]string `json:"agent_labels,omitempty"`

	// BaseDomain Base domain for the cluster (e.g., "example.com")
	BaseDomain *string `json:"base_domain,omitempty"`

	// InfraEnv Name of the InfraEnv to use (for baremetal)
	InfraEnv *string `json:"infra_env,omitempty"`

	// Platform Target platform for the cluster
	Platform *ACMProviderHintsPlatform `json:"platform,omitempty"`

	// ReleaseImage Optional override for the release image
	ReleaseImage *string `json:"release_image,omitempty"`
}

// ACMProviderHintsPlatform Target platform for the cluster
type ACMProviderHintsPlatform string

// ClusterInstance A cluster resource managed by ACM/HyperShift
type ClusterInstance struct {
	// ApiEndpoint Kubernetes API endpoint URL (available when READY)
	ApiEndpoint *string `json:"api_endpoint,omitempty"`

	// ConsoleUri OpenShift console URI (available when READY)
	ConsoleUri *string `json:"console_uri,omitempty"`

	// CreateTime Timestamp when the cluster was created
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Metadata Optional metadata for the cluster
	Metadata *ClusterMetadata `json:"metadata,omitempty"`

	// Nodes Node configuration for the cluster
	Nodes ClusterNodes `json:"nodes"`

	// Path Resource path for this cluster
	Path *string `json:"path,omitempty"`

	// ProviderHints Provider-specific configuration hints
	ProviderHints *ProviderHints `json:"provider_hints,omitempty"`

	// Status Current status of the cluster
	Status *ClusterStatus `json:"status,omitempty"`

	// StatusMessage Human-readable message about the current status
	StatusMessage *string `json:"status_message,omitempty"`

	// UpdateTime Timestamp when the cluster was last updated
	UpdateTime *time.Time `json:"update_time,omitempty"`

	// Version OpenShift version for the cluster (e.g., "4.14.0", "4.15.2")
	Version string `json:"version"`
}

// ClusterListResponse Paginated list of clusters
type ClusterListResponse struct {
	// NextPageToken Token to fetch the next page of results
	NextPageToken *string `json:"next_page_token,omitempty"`

	// Results List of clusters
	Results *[]ClusterInstance `json:"results,omitempty"`
}

// ClusterMetadata Optional metadata for the cluster
type ClusterMetadata struct {
	// Annotations Key-value annotations for the cluster
	Annotations *map[string]string `json:"annotations,omitempty"`

	// Labels Key-value labels for the cluster
	Labels *map[string]string `json:"labels,omitempty"`
}

// ClusterNodes Node configuration for the cluster
type ClusterNodes struct {
	// ControlPlane Control plane node specification
	ControlPlane ControlPlaneSpec `json:"control_plane"`

	// Workers Worker node specification
	Workers *WorkerSpec `json:"workers,omitempty"`
}

// ClusterStatus Current status of the cluster
type ClusterStatus string

// ControlPlaneSpec Control plane node specification
type ControlPlaneSpec struct {
	// Count Number of control plane nodes
	Count int `json:"count"`

	// Cpu Number of CPU cores per control plane node
	Cpu int `json:"cpu"`

	// Memory Memory per control plane node (e.g., "16GB", "32GB")
	Memory string `json:"memory"`

	// Storage Storage per control plane node (e.g., "120GB", "500GB")
	Storage *string `json:"storage,omitempty"`
}

// Error RFC 7807 compliant error response
type Error struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Instance Unique identifier for this specific error occurrence. Useful for
	// tracking and debugging.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int32 `json:"status,omitempty"`

	// Title Short, human-readable summary of the problem
	Title string `json:"title"`

	// Type URI reference identifying the problem type. This is the canonical
	// error code.
	Type ErrorType `json:"type"`
}

// ErrorType URI reference identifying the problem type. This is the canonical
// error code.
type ErrorType string

// Health Health status singleton resource
type Health struct {
	// Checks Individual health checks
	Checks *[]HealthCheck `json:"checks,omitempty"`

	// Message Optional message about the health status
	Message *string `json:"message,omitempty"`

	// Path Canonical path of the resource
	Path *string `json:"path,omitempty"`

	// Status Health status
	Status HealthStatus `json:"status"`
}

// HealthStatus Health status
type HealthStatus string

// HealthCheck Individual health check result
type HealthCheck struct {
	// Message Optional message about this check
	Message *string `json:"message,omitempty"`

	// Name Name of the health check
	Name string `json:"name"`

	// Status Status of this check
	Status HealthCheckStatus `json:"status"`
}

// HealthCheckStatus Status of this check
type HealthCheckStatus string

// ProviderHints Provider-specific configuration hints
type ProviderHints struct {
	// Acm ACM-specific provider hints
	Acm *ACMProviderHints `json:"acm,omitempty"`
}

// WorkerSpec Worker node specification
type WorkerSpec struct {
	// Count Number of worker nodes
	Count int `json:"count"`

	// Cpu Number of CPU cores per worker node
	Cpu int `json:"cpu"`

	// Memory Memory per worker node (e.g., "16GB", "32GB")
	Memory string `json:"memory"`

	// Storage Storage per worker node (e.g., "120GB", "500GB")
	Storage *string `json:"storage,omitempty"`
}

// ClusterPath defines model for ClusterPath.
type ClusterPath = string

// ListClustersParams defines parameters for ListClusters.
type ListClustersParams struct {
	// PageToken Token for fetching the next page of results
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`

	// MaxPageSize Maximum number of results to return per page
	MaxPageSize *int32 `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`
}

// CreateClusterParams defines parameters for CreateCluster.
type CreateClusterParams struct {
	// Id Client-assigned cluster identifier
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// CreateClusterJSONRequestBody defines body for CreateCluster for application/json ContentType.
type CreateClusterJSONRequestBody = ClusterInstance
